# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

   config.vm.define "web" do |box|
      box.vm.box = "ubuntu/bionic64"
      box.vm.hostname = "web"
      
      box.vm.provider "virtualbox" do |vbox|
         vbox.name = "web"
         vbox.memory = 2000
         vbox.cpus = 1
      end
   end

   config.vm.provision "ansible" do |ansible|
     ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
     ansible.become = true
     ansible.become_user = "root"
     ansible.playbook = "playbook.yml"
   end 

end
